### PR TITLE
Pin code flow

### PR DESCRIPTION
**Pull request by viniciusarre**

### CODE REVIEW

**Comment by esron** [comment]
Hi @viniciusarre, thank you for your contribution.

I'm trying to keep the routes in accord with the RESTful pattern.

Also, I'm trying not to repeat code.

There's already a user controller. You could simply use it to update only the pin code.

**Comment by viniciusarre** [comment]
Hi @esron, thank you for your comments! They were very pertinent! 

I have improved a bit upon it, I think there probably could be some improvements...

I have a question: why not export functions explicitly instead of assigning them to an Object? Wouldn't it be a bit more efficient to work on it directly, without the need of assigning it to a constant? (Please check `UserController.js` for more info. I can revert it back to the way it was before, if it's a development decision, as well as refactor it in another PR, please, let me know your thoughts!

Thanks! I look forward to hearing your thoughts on it!

**Comment by esron** [comment]
@viniciusarre , That part of assign to an object was a rookie mistake, at that time I was not familiar with JavaScript for node. You can feel free to rearrange things. 

Code is always improving and changing to better. 👍

**Comment by viniciusarre** [comment]
Hi @esron 

I have pushed a few more changes, I think it should be ready to be merged now! Let me know your thoughts on it! When it's merged, I will work on the other improvements we talked about in this thread. Thanks!

**Pull request merged**
