### PR TITLE
token issuing logic

### PR DESCRIPTION
**Pull request by jhidalgoesp**
Added jwt issuing and middleware logic

### CODE REVIEW

**Comment by esron** [comment]
Hi @jhidalgoesp 

First I would like to say thank you for your efforts in helping me in this project.

I should point that I'm using the [Express Validator ](https://express-validator.github.io/docs/) to validate the requests. It actually helps you to make the errors responses more concise. So, if you add that it would be nice.

Also I'm accepting suggestions to make the issues more informative.

**Comment by jhidalgoesp** [comment]
Ok, i added validations for the name/password.  I kept the username plus password matches validation on the controller method, just changed it to use the Express Validator format.  Thanks for your feedback, just tell me if anything else needs to be done .

**Comment by esron** [comment]
I just noticed now, I'm would like to use the user email for authentication, the name is just for exhibition.

So, if it is not much trouble, could you change the name for the email for authentication?

Thank you.

**Comment by jhidalgoesp** [comment]
Sure, it's done.

**Comment by esron** [comment]
Awesome.

**Pull request merged**
